# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: hook-service
  path.config: "/usr/share/logstash/pipeline/hook-service.conf"
- pipeline.id: another-service
  path.config: "/usr/share/logstash/pipeline/another-service.conf"
